export interface LegalSection {
  heading: string
  paragraphs: string[]
}

export interface LegalDoc {
  title: string
  lastUpdated: string
  sections: LegalSection[]
}

const CONTACT_EMAIL = 'vanshkapoor2905@gmail.com'

// Bump this when the policy or terms change materially — users are re-prompted
// to accept when their recorded consent version no longer matches.
export const LEGAL_VERSION = '2026-06-10'

export const PRIVACY_POLICY: LegalDoc = {
  title: 'Privacy Policy',
  lastUpdated: 'June 10, 2026',
  sections: [
    {
      heading: 'Overview',
      paragraphs: [
        'GymTracker ("the App") helps you plan, log, and review your workouts. This policy explains what information the App collects, how it is used, and the choices you have. When you first sign in, you are asked to review and accept this policy before using the App.',
      ],
    },
    {
      heading: 'Information We Collect',
      paragraphs: [
        'Account information: when you sign in with Google, we receive your name, email address, and profile photo from your Google account. We never see your Google password.',
        'Fitness profile: information you choose to provide during onboarding or in Settings, such as biological sex, age, height, body weight, body fat percentage, fitness level, and training goals. Providing this is optional and requires your explicit consent; it is used to estimate calories burned.',
        'Workout data: the workouts, exercises, sets, reps, weights, durations, and rest times you log, along with derived values such as estimated calories.',
        'Coach conversations: messages you send to the in-app AI coach and the responses you receive.',
        'Technical data: like most web services, our hosting provider (Netlify) and Google Firebase automatically record technical information when you use the App, such as your IP address, browser type, and request timestamps, in standard server logs used for security and operations.',
      ],
    },
    {
      heading: 'How Your Information Is Used',
      paragraphs: [
        'To provide the App’s core features: logging workouts, showing your history and progress, and estimating calories burned.',
        'To personalize the experience, such as suggesting recent weights and showing your last session for an exercise.',
        'To answer questions you ask the AI coach. When you use the coach, your message and relevant workout context are sent to Anthropic, the AI provider that generates the response.',
        'We do not sell your personal information, and we do not use it for advertising.',
      ],
    },
    {
      heading: 'Where Your Data Is Stored',
      paragraphs: [
        'Your data is stored in Google Firebase (Firestore and Firebase Authentication), operated by Google LLC. Data is protected by per-user access rules: your data is only readable by your authenticated account.',
        'Standard service providers we rely on (Google Firebase, Netlify for hosting, and Anthropic for the coach feature) process data only as needed to operate the App.',
      ],
    },
    {
      heading: 'AI Coach & Anthropic',
      paragraphs: [
        'Coach responses are generated by Anthropic’s Claude models via Anthropic’s commercial API. To answer your question, your message and relevant context (such as recent workout history and, if you provided it, fitness profile details) are sent to Anthropic for processing.',
        'Under Anthropic’s commercial API terms, data submitted through the API is not used to train Anthropic’s models. Anthropic may retain API data for a limited period for abuse and safety monitoring, after which it is deleted. See Anthropic’s own privacy documentation for details.',
        'If you prefer that none of your data reaches Anthropic, simply do not use the coach feature — all other features work without it.',
      ],
    },
    {
      heading: 'Health and Fitness Data',
      paragraphs: [
        'Workout logs and fitness profile details (such as body weight and body fat percentage) are health-related information. This data is collected only with your consent and used only for the features described in this policy — your training history and calorie estimates.',
        'Calorie figures are estimates based on standard MET formulas and your profile; they are not medical measurements.',
        'You can decline or withdraw consent for the fitness profile at any time and still use the App; calorie estimates are simply unavailable without it.',
      ],
    },
    {
      heading: 'Your Rights',
      paragraphs: [
        'Access: all data the App holds about you is visible inside the App — your profile in Settings, your workouts in the Calendar, and your coach conversations in the Coach tab.',
        'Withdrawal of consent: you can withdraw consent for health-related data at any time by removing your fitness profile information in Settings or by deleting your account. Declining the optional fitness profile never restricts your use of the rest of the App.',
        'Deletion: you can delete individual workouts, sets, exercises, and coach conversations inside the App, or delete your entire account and all associated data at any time via Settings → Account → Delete Account.',
        'Depending on where you live, you may have additional rights (such as data portability or the right to lodge a complaint with a supervisory authority). Contact us to exercise them.',
      ],
    },
    {
      heading: 'Data Retention & Deletion',
      paragraphs: [
        'Your data is retained for as long as your account exists so that your workout history remains available to you.',
        'You can permanently delete your account and all associated data yourself, at any time, via Settings → Account → Delete Account. Deletion is immediate and cannot be undone. For security, you will be asked to re-confirm your Google sign-in first.',
        `If you prefer, you can instead contact us at ${CONTACT_EMAIL} and we will delete your account and data within 30 days.`,
        'Deletion removes your data from our systems. Residual copies in technical server logs (see "Information We Collect") and any data retained by Anthropic for its limited safety-monitoring period expire on those providers’ standard schedules.',
      ],
    },
    {
      heading: 'Children',
      paragraphs: [
        'The App is not directed at children under 13 (or the minimum age in your jurisdiction), and we do not knowingly collect data from them.',
      ],
    },
    {
      heading: 'Changes to This Policy',
      paragraphs: [
        'We may update this policy from time to time. The "last updated" date above always reflects the current version, and we will notify you of material changes via the App or email and ask you to review and accept the updated policy.',
      ],
    },
    {
      heading: 'Contact',
      paragraphs: [
        `Questions about this policy or your data? Contact ${CONTACT_EMAIL}.`,
      ],
    },
  ],
}

export const TERMS_OF_USE: LegalDoc = {
  title: 'Terms of Use',
  lastUpdated: 'June 10, 2026',
  sections: [
    {
      heading: 'Acceptance of Terms',
      paragraphs: [
        'When you first sign in to GymTracker ("the App"), you are asked to review and accept these Terms of Use and the Privacy Policy. By accepting, you agree to be bound by them. If you do not agree, do not use the App.',
      ],
    },
    {
      heading: 'Eligibility',
      paragraphs: [
        'You must be at least 13 years old — or the age of digital consent in your jurisdiction, if higher — and have the legal capacity to agree to these terms. By using the App you represent that you meet these requirements.',
      ],
    },
    {
      heading: 'The Service',
      paragraphs: [
        'The App lets you plan workout programs, log training sessions, review your history, estimate calories burned, and chat with an AI coach. The App is provided free of charge and may change, gain, or lose features at any time.',
      ],
    },
    {
      heading: 'License & Intellectual Property',
      paragraphs: [
        'The App, including its design, code, and content (excluding the data you log), is owned by us and protected by applicable intellectual property laws.',
        'We grant you a limited, personal, non-exclusive, non-transferable, revocable license to use the App for your own non-commercial fitness tracking. You may not copy, modify, distribute, sell, or lease any part of the App.',
      ],
    },
    {
      heading: 'Not Medical Advice',
      paragraphs: [
        'The App, including calorie estimates and AI coach responses, provides general fitness information only. It is not medical advice, diagnosis, or treatment, and it is not a substitute for guidance from a qualified physician, physiotherapist, or certified trainer.',
        'Consult a medical professional before starting or changing an exercise program, especially if you have any medical condition. Stop exercising and seek medical attention if you feel pain, dizziness, or discomfort.',
      ],
    },
    {
      heading: 'Assumption of Risk',
      paragraphs: [
        'Physical exercise carries inherent risks, including injury. You are solely responsible for exercising within your own limits and for using appropriate equipment and technique. You use the App and perform any logged activity at your own risk.',
      ],
    },
    {
      heading: 'AI Coach',
      paragraphs: [
        'Coach responses are generated by an AI model provided by Anthropic and may be inaccurate, incomplete, or unsuitable for your situation. Use your own judgment and verify important information independently.',
      ],
    },
    {
      heading: 'Your Account & Acceptable Use',
      paragraphs: [
        'You are responsible for the Google account you sign in with and for the accuracy of the information you log.',
        'You agree not to misuse the App, including attempting to access other users’ data, disrupting the service, reverse engineering it, or using it for unlawful purposes.',
      ],
    },
    {
      heading: 'Your Content',
      paragraphs: [
        'You retain ownership of the data you log. You grant us the limited rights needed to store and process that data solely to operate the App, as described in the Privacy Policy.',
      ],
    },
    {
      heading: 'Disclaimer & Limitation of Liability',
      paragraphs: [
        'The App is provided "as is" and "as available", without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy, or uninterrupted availability.',
        'To the maximum extent permitted by law, we are not liable for any indirect, incidental, special, or consequential damages, or for any injury, health outcome, or data loss arising from your use of the App.',
        'To the maximum extent permitted by law, our total aggregate liability for any claims arising out of or relating to the App shall not exceed one US dollar (US $1).',
      ],
    },
    {
      heading: 'Termination',
      paragraphs: [
        'You may stop using the App at any time and delete your account and all associated data directly in the App (Settings → Account → Delete Account), or request deletion as described in the Privacy Policy. We may suspend or terminate access for misuse of the service.',
      ],
    },
    {
      heading: 'Governing Law',
      paragraphs: [
        'These terms are governed by the laws of the State of Arizona, USA, without regard to its conflict-of-laws rules. Any dispute arising out of these terms or the App shall be brought exclusively in the state or federal courts located in Arizona, and you consent to their jurisdiction.',
      ],
    },
    {
      heading: 'Severability',
      paragraphs: [
        'If any provision of these terms is found to be unenforceable, that provision will be limited or removed to the minimum extent necessary, and the remaining provisions will remain in full force and effect.',
      ],
    },
    {
      heading: 'Changes to These Terms',
      paragraphs: [
        'We may update these terms from time to time. The "last updated" date above always reflects the current version, and we will notify you of material changes via the App or email and ask you to review and accept the updated terms.',
      ],
    },
    {
      heading: 'Contact',
      paragraphs: [
        `Questions about these terms? Contact ${CONTACT_EMAIL}.`,
      ],
    },
  ],
}
